# Generated by Django 4.2.13 on 2026-04-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enterprise_type",
                    models.CharField(db_column="Тип предприятия", max_length=255),
                ),
                (
                    "enterprise_code",
                    models.CharField(
                        db_column="Код предприятия", db_index=True, max_length=10
                    ),
                ),
                ("host_count", models.IntegerField(db_column="Количество хостов")),
                (
                    "threat_code",
                    models.IntegerField(
                        db_column="Код реализованной угрозы", db_index=True
                    ),
                ),
                ("success", models.BooleanField(db_column="Успех")),
                (
                    "region",
                    models.CharField(
                        db_column="Регион размещения предприятия", max_length=255
                    ),
                ),
                ("incident_date", models.DateField(db_column="Дата инцидента")),
                ("incident_time", models.DateTimeField(db_column="Региональное время")),
            ],
            options={
                "verbose_name": "Инцидент безопасности",
                "db_table": "security_incidents",
            },
        ),
        migrations.CreateModel(
            name="GeneratedIncident",
            fields=[
                (
                    "incident_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="security_app.incident",
                    ),
                ),
                ("generation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("confidence_score", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Сгенерированный инцидент",
                "db_table": "generated_incidents",
            },
            bases=("security_app.incident",),
        ),
        migrations.CreateModel(
            name="Threat",
            fields=[
                (
                    "threat_id",
                    models.IntegerField(
                        db_column="Идентификатор УБИ", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="Наименование УБИ", max_length=500),
                ),
                ("description", models.TextField(db_column="Описание")),
                ("threat_source", models.TextField(db_column="Источник угрозы")),
                (
                    "target_object",
                    models.CharField(db_column="Объект воздействия", max_length=255),
                ),
                (
                    "confidentiality_breach",
                    models.BooleanField(db_column="Нарушение конфиденциальности"),
                ),
                (
                    "integrity_breach",
                    models.BooleanField(db_column="Нарушение целостности"),
                ),
                (
                    "availability_breach",
                    models.BooleanField(db_column="Нарушение доступности"),
                ),
                (
                    "date_added",
                    models.DateField(db_column="Дата включения угрозы в БнД УБИ"),
                ),
                (
                    "last_modified",
                    models.DateField(db_column="Дата последнего изменения данных"),
                ),
                ("status", models.CharField(db_column="Статус угрозы", max_length=50)),
                (
                    "notes",
                    models.TextField(blank=True, db_column="Замечания", null=True),
                ),
            ],
            options={
                "verbose_name": "Угроза ФСТЭК",
                "db_table": "fstec_threats",
                "indexes": [
                    models.Index(
                        fields=["status"], name="fstec_threa_Статус _556f5a_idx"
                    ),
                    models.Index(
                        fields=["target_object"], name="fstec_threa_Объект _3d7d7a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["incident_date", "threat_code"],
                name="security_in_Дата ин_c7bfd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["region", "enterprise_type"],
                name="security_in_Регион _ad0411_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["-incident_time"], name="security_in_Региона_9e5b9e_idx"
            ),
        ),
        migrations.AddField(
            model_name="generatedincident",
            name="source_incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_derivatives",
                to="security_app.incident",
            ),
        ),
    ]
