# Generated by Django 4.2.13 on 2026-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="host_count",
            field=models.IntegerField(db_column="Количество хостов", default=0),
        ),
        migrations.AlterField(
            model_name="incident",
            name="success",
            field=models.BooleanField(db_column="Успех", default=False),
        ),
    ]
