# Generated by Django 4.2.13 on 2026-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_app", "0002_alter_incident_host_count_alter_incident_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threat",
            name="target_object",
            field=models.CharField(db_column="Объект воздействия"),
        ),
    ]
