# Generated by Django 4.2.13 on 2026-04-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0003_alter_threat_target_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedIncident',
        ),
    ]
